const CLOUDINARY_API_KEY = process.env['CLOUDINARY_API_KEY']
const CLOUDINARY_CLOUD_NAME = process.env['CLOUDINARY_CLOUD_NAME']
const CLOUDINARY_API_SECRET = process.env['CLOUDINARY_API_SECRET']

const CLOUDINARY_API_KEY_PRO = process.env['CLOUDINARY_API_KEY_PRO']
const CLOUDINARY_CLOUD_NAME_PRO = process.env['CLOUDINARY_CLOUD_NAME_PRO']
const CLOUDINARY_API_SECRET_PRO = process.env['CLOUDINARY_API_SECRET_PRO']

module.exports = {
  CLOUDINARY_API_KEY,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_SECRET,
  CLOUDINARY_API_KEY_PRO,
  CLOUDINARY_CLOUD_NAME_PRO,
  CLOUDINARY_API_SECRET_PRO

}
