// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models

module.exports = (mongoose, Mongoose) => {
  // This section contains the properties of your model, mapped to your collection's properties.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const schema = Mongoose.Schema({
    'first_name': String,
    'image': {
      'url': String,
      'public_id': String,
    },
    'modality': [String],
    'plan': [String],
    'deleted': Boolean,
    'email': String,
    'last_name': String,
    'password': String,
    'dni': String,
    'professionalId': String,
    'country': String,
    'state': String,
    'city': String,
    'zip': String,
    'scheduleDays': String,
    'scheduleHours': String,
    'rating': Number,
    'specialities': { type: Mongoose.Schema.Types.ObjectId, ref: 'specialities' },
  }, {
    timestamps: false,
  });

  return mongoose.model('professionals', schema, 'professionals');
};
