// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models

module.exports = (mongoose, Mongoose) => {
  // This section contains the properties of your model, mapped to your collection's properties.
  // Learn more here: https://docs.forestadmin.com/documentation/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const schema = Mongoose.Schema({
    'first_name': String,
    'last_name': String,
    'DNI': Number,
    'country': String,
    'state': String,
    'city': String,
    'postcode': Number,
    'address': String,
    'email': String,
    'password': String,
    'image': {
      'url': String,
      'public_id': String,
    },
    'role': [String],
    'plan': [String],
    'deleted': Boolean,
  }, {
    timestamps: false,
  });

  return mongoose.model('users', schema, 'users');
};
